# Generated by Django 4.2.1 on 2024-04-28 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='license',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('sport', models.CharField(blank=True, max_length=200)),
                ('current_activity', models.CharField(blank=True, max_length=1000)),
                ('date_of_injury', models.DateField(null=True)),
                ('knee', models.CharField(blank=True, max_length=50)),
                ('mechanism_injury', models.CharField(blank=True, max_length=1000)),
                ('other_injuries', models.CharField(blank=True, max_length=4000)),
                ('injuries_same', models.IntegerField(null=True)),
                ('injuries_other', models.IntegerField(null=True)),
                ('reconstructions_same', models.IntegerField(null=True)),
                ('reconstructions_other', models.IntegerField(null=True)),
                ('planned_management', models.CharField(blank=True, max_length=500)),
                ('survey_date', models.DateTimeField(null=True)),
                ('doctors_history', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='open', max_length=50)),
                ('percentage', models.IntegerField(null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
