# Generated by Django 4.2.1 on 2024-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_doctoruser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='doctoruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='doctoruser',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
