# Generated by Django 4.2.1 on 2024-04-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_baseuser_license_demographics'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
