# Generated by Django 4.2.1 on 2024-04-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_demographics_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='date_of_injury',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='survey_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
