# Generated by Django 4.2.1 on 2024-05-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_demographics_date_of_injury_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='current_phase',
            field=models.CharField(default='Demographics', max_length=50),
        ),
        migrations.CreateModel(
            name='PreOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('passive_extension', models.IntegerField(null=True)),
                ('passive_flexion', models.IntegerField(null=True)),
                ('swelling', models.CharField(blank=True, max_length=50, null=True)),
                ('dynamometer_affected', models.IntegerField(null=True)),
                ('dynamometer_non_affected', models.IntegerField(null=True)),
                ('dynamometer_symmetry', models.FloatField(null=True)),
                ('hop_trial_1', models.IntegerField(null=True)),
                ('hop_trial_2', models.IntegerField(null=True)),
                ('hop_symmetry', models.IntegerField(null=True)),
                ('percentage', models.FloatField(null=True)),
                ('draft', models.BooleanField(default=True)),
                ('demographics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Phase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(null=True)),
                ('draft', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('prone_hang', models.IntegerField(null=True)),
                ('passive_flexion', models.IntegerField(null=True)),
                ('swelling', models.CharField(blank=True, max_length=50, null=True)),
                ('functional_alignment', models.CharField(blank=True, max_length=50, null=True)),
                ('bridge_affected', models.IntegerField(null=True)),
                ('bridge_non_affected', models.IntegerField(null=True)),
                ('bridge_hurdle', models.CharField(blank=True, max_length=50, null=True)),
                ('bridge_symmetry', models.FloatField(null=True)),
                ('calf_affected', models.IntegerField(null=True)),
                ('calf_non_affected', models.IntegerField(null=True)),
                ('calf_hurdle', models.CharField(blank=True, max_length=50, null=True)),
                ('calf_symmetry', models.FloatField(null=True)),
                ('endurance_affected', models.IntegerField(null=True)),
                ('endurance_non_affected', models.IntegerField(null=True)),
                ('endurance_hurdle', models.CharField(blank=True, max_length=50, null=True)),
                ('endurance_symmetry', models.FloatField(null=True)),
                ('leg_rise_affected', models.IntegerField(null=True)),
                ('leg_rise_non_affected', models.IntegerField(null=True)),
                ('leg_rise_hurdle', models.CharField(blank=True, max_length=50, null=True)),
                ('leg_rise_symmetry', models.FloatField(null=True)),
                ('unipedal_open_affected', models.IntegerField(null=True)),
                ('unipedal_closed_affected', models.IntegerField(null=True)),
                ('unipedal_open_non_affected', models.IntegerField(null=True)),
                ('unipedal_closed_non_affected', models.IntegerField(null=True)),
                ('unipedal_affected_hurdel', models.CharField(blank=True, max_length=50, null=True)),
                ('unipedal_non_affected_hurdel', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.FloatField(null=True)),
                ('leg_press_affected', models.IntegerField(null=True)),
                ('leg_press_affected_weight', models.FloatField(null=True)),
                ('leg_press_non_affected', models.IntegerField(null=True)),
                ('leg_press_non_affected_weight', models.FloatField(null=True)),
                ('squat', models.IntegerField(null=True)),
                ('squat_weight', models.FloatField(null=True)),
                ('Demographics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.demographics')),
            ],
        ),
        migrations.CreateModel(
            name='Phase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('date_of_surgery', models.DateField(blank=True, null=True)),
                ('graft', models.CharField(blank=True, max_length=50, null=True)),
                ('passive_extension', models.IntegerField(null=True)),
                ('passive_flexion', models.IntegerField(null=True)),
                ('swelling', models.CharField(blank=True, max_length=50, null=True)),
                ('quads', models.IntegerField(null=True)),
                ('percentage', models.IntegerField(null=True)),
                ('draft', models.BooleanField(default=True)),
                ('Demographics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.demographics')),
            ],
        ),
    ]
