# Generated by Django 4.2.1 on 2024-04-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_doctor_experience_alter_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
