# Generated by Django 4.2.1 on 2024-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(null=True),
        ),
    ]
