# Generated by Django 4.2.1 on 2024-04-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_doctor_managers_doctor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
